repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0 
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-aws-credentials
    -   id: requirements-txt-fixer
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8