repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0 
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: detect-aws-credentials
        args: [--allow-missing-credentials ]
# -   repo: https://gitlab.com/pycqa/flake8
#     rev: 3.7.9
#     hooks:
#     - id: flake8